exec sp_addrolemember 'db_datareader', 'chirpuser';
exec sp_addrolemember 'db_datawriter', 'chirpuser';

GRANT EXECUTE ON [dbo].aspnet_CheckSchemaVersion to chirpuser;
GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByUserId TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByName TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByEmail TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_GetPassword TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_GetPasswordWithFormat TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_UpdateUserInfo TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_GetNumberOfUsersOnline TO chirpuser
GRANT EXECUTE ON dbo.aspnet_CheckSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_RegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UnRegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByUserId TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByName TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByEmail TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_GetAllUsers TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_GetNumberOfUsersOnline TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_FindUsersByName TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_FindUsersByEmail TO chirpuser
GRANT EXECUTE ON dbo.aspnet_CheckSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_RegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UnRegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Users_DeleteUser TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_CreateUser TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_SetPassword TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_ResetPassword TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_UpdateUser TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_ChangePasswordQuestionAndAnswer TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Membership_UnlockUser TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_Applications TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_Users TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_MembershipUsers TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Paths_CreatePath TO chirpuser
GRANT EXECUTE ON dbo.aspnet_PersonalizationAllUsers_GetPageSettings TO chirpuser
GRANT EXECUTE ON dbo.aspnet_PersonalizationPerUser_GetPageSettings TO chirpuser
GRANT EXECUTE ON dbo.aspnet_PersonalizationAllUsers_ResetPageSettings TO chirpuser
GRANT EXECUTE ON dbo.aspnet_PersonalizationPerUser_ResetPageSettings TO chirpuser
GRANT EXECUTE ON dbo.aspnet_PersonalizationAllUsers_SetPageSettings TO chirpuser
GRANT EXECUTE ON dbo.aspnet_PersonalizationPerUser_SetPageSettings TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Personalization_GetApplicationId TO chirpuser
GRANT EXECUTE ON dbo.aspnet_CheckSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_RegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UnRegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_PersonalizationAdministration_FindState TO chirpuser
GRANT EXECUTE ON dbo.aspnet_PersonalizationAdministration_GetCountOfState TO chirpuser
GRANT EXECUTE ON dbo.aspnet_CheckSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_RegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UnRegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_PersonalizationAdministration_ResetUserState TO chirpuser
GRANT EXECUTE ON dbo.aspnet_PersonalizationAdministration_ResetSharedState TO chirpuser
GRANT EXECUTE ON dbo.aspnet_PersonalizationAdministration_DeleteAllState TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_Applications TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_Users TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_WebPartState_Paths TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_WebPartState_Shared TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_WebPartState_User TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Profile_GetProperties TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Profile_SetProperties TO chirpuser
GRANT EXECUTE ON dbo.aspnet_CheckSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_RegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UnRegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Profile_GetNumberOfInactiveProfiles TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Profile_GetProfiles TO chirpuser
GRANT EXECUTE ON dbo.aspnet_CheckSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_RegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UnRegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Profile_DeleteProfiles TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Profile_DeleteInactiveProfiles TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_Applications TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_Users TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_Profiles TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UsersInRoles_IsUserInRole TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UsersInRoles_GetRolesForUser TO chirpuser
GRANT EXECUTE ON dbo.aspnet_CheckSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_RegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UnRegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UsersInRoles_IsUserInRole TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UsersInRoles_GetRolesForUser TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Roles_RoleExists TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UsersInRoles_GetUsersInRoles TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UsersInRoles_FindUsersInRole TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Roles_GetAllRoles TO chirpuser
GRANT EXECUTE ON dbo.aspnet_CheckSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_RegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UnRegisterSchemaVersion TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Roles_CreateRole TO chirpuser
GRANT EXECUTE ON dbo.aspnet_Roles_DeleteRole TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UsersInRoles_AddUsersToRoles TO chirpuser
GRANT EXECUTE ON dbo.aspnet_UsersInRoles_RemoveUsersFromRoles TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_Applications TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_Users TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_Roles TO chirpuser
GRANT SELECT ON dbo.vw_aspnet_UsersInRoles TO chirpuser
